name: Release CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  x64_build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install MFC libraries
      run: choco install visualstudio2022-workload-vctools --package-parameters "--add Microsoft.VisualStudio.Component.VC.ATLMFC" -y

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1.3

    - name: Run msbuild for x64
      run: msbuild TrafficMonitor.sln -p:Configuration=Release -p:Platform=x64 -p:PlatformToolset=v142

    - name: Get current time
      uses: josStorer/get-current-time@v2.0.2
      id: current-time
      with:
        format: YYYYMMDD_HHmmss
        utcOffset: "+08:00"

    - name: Upload x64 artifact
      uses: actions/upload-artifact@v3
      with:
        name: x64_${{ steps.current-time.outputs.formattedTime }}_TrafficMonitor
        path: |
          Bin/x64/Release/TrafficMonitor.exe
          Bin/x64/Release/*.dll
