name: Release CI
on:
  push:
    tags: # Запускается при пуше тега
      - "v*"

jobs:
  x64_build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1.3
      
    - name: Run msbuild
      run: msbuild -p:configuration=release -p:platform=x64 -p:platformToolset=v142
      
    - name: Get current time
      uses: josStorer/get-current-time@v2.0.2
      id: current-time
      with:
        format: YYYYMMDD_HHmmss
        utcOffset: "+08:00"
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: x64_${{ steps.current-time.outputs.formattedTime }}_TrafficMonitor
        path: |
          Bin/x64/Release/TrafficMonitor.exe
          Bin/x64/Release/*.dll

    - name: Upload pdb files
      uses: actions/upload-artifact@v3
      with:
        name: x64_${{ steps.current-time.outputs.formattedTime }}_pdb
        path: Bin/x64/Release/*.pdb

    - name: Create GitHub Release
      if: ${{ github.ref_type == 'tag' }}
      uses: softprops/action-gh-release@v1
      with:
        files: |
          Bin/x64/Release/TrafficMonitor.exe
          Bin/x64/Release/*.dll
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  x86_build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1.3
      
    - name: Run msbuild
      run: msbuild -p:configuration=release -p:platform=x86 -p:platformToolset=v142
      
    - name: Get current time
      uses: josStorer/get-current-time@v2.0.2
      id: current-time
      with:
        format: YYYYMMDD_HHmmss
        utcOffset: "+08:00"
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: x86_${{ steps.current-time.outputs.formattedTime }}_TrafficMonitor
        path: |
          Bin/Release/TrafficMonitor.exe
          Bin/Release/*.dll
      
    - name: Upload pdb files
      uses: actions/upload-artifact@v3
      with:
        name: x86_${{ steps.current-time.outputs.formattedTime }}_pdb
        path: Bin/Release/*.pdb

    - name: Create GitHub Release
      if: ${{ github.ref_type == 'tag' }}
      uses: softprops/action-gh-release@v1
      with:
        files: |
          Bin/Release/TrafficMonitor.exe
          Bin/Release/*.dll
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
